
spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/630461866/nz1905.git
          search-paths: respo


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/